-- ============= ITEM ===============================================

truncate item;
insert into item (id,tier,ranking,name,label,type,image,attributes,created,updated) values
(10001,null,null,'wood','WOOD','gather','/images/item/wood.png','{}',now(),now()),
(10002,null,null,'stone','STONE','gather','/images/item/stone.png','{}',now(),now()),
(10003,null,null,'coal','COAL','gather','/images/item/coal.png','{}',now(),now()),
(10004,null,null,'iron-ore','IRON ORE','gather','/images/item/iron-ore.png','{}',now(),now()),
(10005,null,null,'gold-ore','GOLD ORE','gather','/images/item/gold-ore.png','{}',now(),now()),
(10006,null,null,'platinum','PLATINUM','gather','/images/item/platinum.png','{}',now(),now()),
(10007,null,null,'tanzanite','TANZANITE','gather','/images/item/tanzanite.png','{}',now(),now()),
(10008,null,null,'emerald','EMERALD','gather','/images/item/emerald.png','{}',now(),now()),
(10009,null,null,'ruby','RUBY','gather','/images/item/ruby.png','{}',now(),now()),
(10010,null,null,'jade','JADE','gather','/images/item/jade.png','{}',now(),now()),
(10011,null,null,'insatiable-ore','INSATIABLE ORE','gather','/images/item/insatiable-ore.png','{}',now(),now()),
(10012,null,null,'insatiable-cracked-stone','INSATIABLE CRACKED STONE','gather','/images/item/insatiable-cracked-stone.png','{}',now(),now()),
(10013,null,null,'material-for-the-enhance-stone-red','MATERIAL FOR THE ENHANCE STONE (RED)','gather','/images/item/material-for-the-enhance-stone-red.png','{}',now(),now()),
(10014,null,null,'material-for-the-enhance-stone-yellow','MATERIAL FOR THE ENHANCE STONE (YELLOW)','gather','/images/item/material-for-the-enhance-stone-yellow.png','{}',now(),now()),
(10015,null,null,'material-for-the-enhance-stone-green','MATERIAL FOR THE ENHANCE STONE (GREEN)','gather','/images/item/material-for-the-enhance-stone-green.png','{}',now(),now()),
(10016,null,null,'material-for-the-enhance-stone-blue','MATERIAL FOR THE ENHANCE STONE (BLUE)','gather','/images/item/material-for-the-enhance-stone-blue.png','{}',now(),now()),
(10101,null,null,'mitar-ore','MITAR ORE','gather','/images/item/mitar-ore.png','{}',now(),now()),




(11001,null,null,'processed-wood','PROCESSED WOOD','crafted','/images/item/processed-wood.png','{}',now(),now()),
(11002,null,null,'iron-bar','IRON BAR','crafted','/images/item/iron-bar.png','{}',now(),now()),
(11003,null,null,'gold-bar','GOLD BAR','crafted','/images/item/gold-bar.png','{}',now(),now()),
(11004,null,null,'platinum-bar','PLATINUM BAR','crafted','/images/item/platinum-bar.png','{}',now(),now()),
(11005,null,null,'tanzanite-essence','TANZANITE ESSENCE','crafted','/images/item/tanzanite-essence.png','{}',now(),now()),
(11006,null,null,'emerald-essence','EMERALD ESSENCE','crafted','/images/item/emerald-essence.png','{}',now(),now()),
(11007,null,null,'ruby-essence','RUBY ESSENCE','crafted','/images/item/ruby-essence.png','{}',now(),now()),
(11008,null,null,'jade-essence','JADE ESSENCE','crafted','/images/item/jade-essence.png','{}',now(),now()),
(11009,null,null,'hp-potion','HP POTION','crafted','/images/item/hp-potion.png','{}',now(),now()),
(11010,null,null,'large-hp-potion','LARGE HP POTION','crafted','/images/item/large-hp-potion.png','{}',now(),now()),
(11011,null,null,'scroll-of-portal','SCROLL OF PORTAL','crafted','/images/item/scroll-of-portal.png','{}',now(),now()),
(11101,null,null,'high-uldreds-pickaxe','HIGH ULDRED\'S PICKAXE','crafted','/images/item/high-uldreds-pickaxe.png','{}',now(),now()),
(11102,null,null,'dwarven-pickaxe','DWARVEN PICKAXE','crafted','/images/item/dwarven-pickaxe.png','{}',now(),now()),

(12001,null,null,'sacred-soul-stone','SACRED SOUL STONE','basics','/images/item/sacred-soul-stone.png','{}',now(),now()),
(12002,null,null,'shard','SHARD','basics','/images/item/shard.png','{}',now(),now()),
(12003,null,null,'money','MONEY','basics','/images/item/money.png','{}',now(),now()),
(12004,null,null,'gems','GEMS','basics','/images/item/gems.png','{}',now(),now()),
(12005,null,null,'trade-coin','TRADE COIN','basics','/images/item/trade-coin.png','{}',now(),now()),


(15001,null,null,'meat','MEAT','drop','/images/item/meat.png','{}',now(),now()),
(15002,null,null,'rat-claw','RAT CLAW','drop','/images/item/rat-claw.png','{}',now(),now()),
(15003,null,null,'slime-drop','SLIME DROP','drop','/images/item/slime-drop.png','{}',now(),now()),
(15004,null,null,'leather','LEATHER','drop','/images/item/leather.png','{}',now(),now()),
(15005,null,null,'oculothorax','OCULOTHORAX','drop','/images/item/oculothorax.png','{}',now(),now()),
(15006,null,null,'magic-dust','MAGIC DUST','drop','/images/item/magic-dust.png','{}',now(),now()),
(15007,null,null,'essence-empty-vial','ESSENCE EMPTY VIAL','drop','/images/item/essence-empty-vial.png','{}',now(),now()),
(15008,null,null,'steak','STEAK','drop','/images/item/steak.png','{}',now(),now()),
(15009,null,null,'demonic-matter','DEMONIC MATTER','drop','/images/item/demonic-matter.png','{}',now(),now()),
(15010,null,null,'bone-dust','BONE DUST','drop','/images/item/bone-dust.png','{}',now(),now()),
(15101,null,null,'stone-scale','STONE SCALE','drop','/images/item/stone-scale.png','{}',now(),now()),


(19901,null,null,'rune-i','RUNE I (R1)','rune','/images/item/rune-i.png','{}',now(),now()),
(19902,null,null,'rune-ii','RUNE II (R2)','rune','/images/item/rune-ii.png','{}',now(),now()),
(19903,null,null,'rune-iii','RUNE III (R3)','rune','/images/item/rune-iii.png','{}',now(),now()),
(19904,null,null,'rune-iv','RUNE IV (R4)','rune','/images/item/rune-iv.png','{}',now(),now()),
(19905,null,null,'rune-v','RUNE V (R5)','rune','/images/item/rune-v.png','{}',now(),now()),
(19906,null,null,'rune-vi','RUNE VI (R6)','rune','/images/item/rune-vi.png','{}',now(),now()),
(19907,null,null,'rune-vii','RUNE VII (R7)','rune','/images/item/rune-vii.png','{}',now(),now()),
(19908,null,null,'rune-viii','RUNE VIII (R8)','rune','/images/item/rune-viii.png','{}',now(),now()),
(19909,null,null,'rune-ix','RUNE IX (R9)','rune','/images/item/rune-ix.png','{}',now(),now()),
(19910,null,null,'rune-x','RUNE X (R10)','rune','/images/item/rune-x.png','{}',now(),now()),
(19911,null,null,'rune-xi','RUNE XI (R11)','rune','/images/item/rune-xi.png','{}',now(),now()),
(19912,null,null,'rune-xii','RUNE XII (R12)','rune','/images/item/rune-xii.png','{}',now(),now()),
(19913,null,null,'rune-xiii','RUNE XIII (R13)','rune','/images/item/rune-xiii.png','{}',now(),now()),


(21001,2,100,'amulet-of-protection','AMULET OF PROTECTION','amulet','/images/item/amulet-of-protection.png','{"health.min":90,"health.max":150,"fire-resist.min":15,"fire-resist.max":35}',now(),now()),
(21002,4,100,'eyes-of-mitar','EYES OF MITAR','amulet','/images/item/eyes-of-mitar.png','{"defense.min":55,"defense.max":80,"fire-damage.min":30,"fire-damage.max":70}',now(),now()),
(21003,5,100,'power-of-mitar','POWER OF MITAR','amulet','/images/item/power-of-mitar.png','{"health.min":150,"health.max":750,"defense.min":30,"defense.max":100,"earth-damage.min":45,"earth-damage.max":100}',now(),now()),
(21004,1,100,'amulet-of-truth','AMULET OF TRUTH','amulet','/images/item/amulet-of-truth.png','{"defense.min":5,"defense.max":10,"earth-resist.min":15,"earth-resist.max":25}',now(),now()),
(21005,2,110,'amulet-of-elements','AMULET OF ELEMENTS','amulet','/images/item/amulet-of-elements.png','{"defense.min":8,"defense.max":30,"fire-damage.min":10,"fire-damage.max":20}',now(),now()),
(21006,3,100,'dwarven-amulet','DWARVEN AMULET','amulet','/images/item/dwarven-amulet.png','{"health.min":150,"health.max":300,"earth-resist.min":15,"earth-resist.max":50}',now(),now()),
(21007,3,100,'amulet-of-strength','AMULET OF STRENGTH','amulet','/images/item/amulet-of-strength.png','{"defense.min":35,"defense.max":60,"fire-damage.min":20,"fire-damage.max":50}',now(),now()),
(21008,4,120,'jewel-of-mitar','JEWEL OF MITAR','amulet','/images/item/jewel-of-mitar.png','{"health.min":300,"health.max":600,"earth-resist.min":40,"earth-resist.max":75}',now(),now()),
(21009,4,130,'depth-of-mitar','DEPTH OF MITAR','amulet','/images/item/depth-of-mitar.png','{"defense.min":50,"defense.max":90,"earth-damage.min":30,"earth-damage.max":70}',now(),now()),
(21010,4,110,'heart-of-mitar','HEART OF MITAR','amulet','/images/item/heart-of-mitar.png','{"health.min":350,"health.max":550,"fire-resist.min":40,"fire-resist.max":75}',now(),now()),
(21011,1,110,'golden-ball-amulet','GOLDEN BALL AMULET','amulet','/images/item/golden-ball-amulet.png','{"defense.min":5,"defense.max":10,"water-resist.min":50,"water-resist.max":75,"wind-resist.min":50,"wind-resist.max":75}',now(),now()),
(21012,1,111,'golden-bricks-amulet','GOLDEN BRICKS AMULET','amulet','/images/item/golden-bricks-amulet.png','{"defense.min":5,"defense.max":10,"water-resist.min":50,"water-resist.max":75,"wind-resist.min":50,"wind-resist.max":75}',now(),now()),
(21013,1,112,'golden-doll-amulet','GOLDEN DOLL AMULET','amulet','/images/item/golden-doll-amulet.png','{"defense.min":5,"defense.max":10,"water-resist.min":50,"water-resist.max":75,"wind-resist.min":50,"wind-resist.max":75}',now(),now()),
(21014,1,113,'golden-horse-amulet','GOLDEN HORSE AMULET','amulet','/images/item/golden-horse-amulet.png','{"defense.min":5,"defense.max":10,"water-resist.min":50,"water-resist.max":75,"wind-resist.min":50,"wind-resist.max":75}',now(),now()),
(21015,1,114,'golden-bear-amulet','GOLDEN BEAR AMULET','amulet','/images/item/golden-bear-amulet.png','{"defense.min":5,"defense.max":10,"water-resist.min":50,"water-resist.max":75,"wind-resist.min":50,"wind-resist.max":75}',now(),now()),
(21016,5,100,'eternal-pyre','ETERNAL PYRE','amulet','/images/item/eternal-pyre.png','{"health.min":150,"health.max":750,"defense.min":30,"defense.max":100,"fire-damage.min":45,"fire-damage.max":100}',now(),now()),
(21017,5,100,'stormforge-amulet','STORMFORGE AMULET','amulet','/images/item/stormforge-amulet.png','{"health.min":150,"health.max":750,"defense.min":30,"defense.max":100,"lightning-damage.min":45,"lightning-damage.max":100}',now(),now()),
(21018,5,100,'oceans-breath','OCEAN\'S BREATH','amulet','/images/item/oceans-breath.png','{"health.min":150,"health.max":750,"defense.min":30,"defense.max":100,"water-damage.min":45,"water-damage.max":100}',now(),now()),
(21019,5,100,'airwhisper-charm','AIRWHISPER CHARM','amulet','/images/item/airwhisper-charm.png','{"health.min":150,"health.max":750,"defense.min":30,"defense.max":100,"wind-damage.min":45,"wind-damage.max":100}',now(),now()),

(22001,1,110,'ring-of-light','RING OF LIGHT','ring','/images/item/ring-of-light.png','{"health.min":200,"health.max":500,"lightning-damage.min":30,"lightning-damage.max":60,"lightning-resist.min":15,"lightning-resist.max":35}',now(),now()),
(22002,1,100,'ring-of-hope','RING OF HOPE','ring','/images/item/ring-of-hope.png','{"health.min":100,"health.max":200,"lightning-resist.min":15,"lightning-resist.max":25}',now(),now()),

(22011,1,120,'ring-of-water','RING OF WATER','ring','/images/item/ring-of-water.png','{"health.min":200,"health.max":500,"water-damage.min":30,"water-damage.max":60,"water-resist.min":15,"water-resist.max":35}',now(),now()),
(22012,1,120,'ring-of-fire','RING OF FIRE','ring','/images/item/ring-of-fire.png','{"health.min":200,"health.max":500,"fire-damage.min":30,"fire-damage.max":60,"fire-resist.min":15,"fire-resist.max":35}',now(),now()),
(22013,1,120,'ring-of-wind','RING OF WIND','ring','/images/item/ring-of-wind.png','{"health.min":200,"health.max":500,"wind-damage.min":30,"wind-damage.max":60,"wind-resist.min":15,"wind-resist.max":35}',now(),now()),
(22014,1,120,'ring-of-earth','RING OF EARTH','ring','/images/item/ring-of-earth.png','{"health.min":200,"health.max":500,"earth-damage.min":30,"earth-damage.max":60,"earth-resist.min":15,"earth-resist.max":35}',now(),now()),

(22021,2,120,'rare-ring-of-water','RARE RING OF WATER','ring','/images/item/rare-ring-of-water.png','{"health.min":220,"health.max":550,"water-damage.min":50,"water-damage.max":100,"water-resist.min":20,"water-resist.max":45}',now(),now()),
(22022,2,120,'rare-ring-of-fire','RARE RING OF FIRE','ring','/images/item/rare-ring-of-fire.png','{"health.min":220,"health.max":550,"fire-damage.min":50,"fire-damage.max":100,"fire-resist.min":20,"fire-resist.max":45}',now(),now()),
(22023,2,120,'rare-ring-of-wind','RARE RING OF WIND','ring','/images/item/rare-ring-of-wind.png','{"health.min":220,"health.max":550,"wind-damage.min":50,"wind-damage.max":100,"wind-resist.min":20,"wind-resist.max":45}',now(),now()),
(22024,2,120,'rare-ring-of-earth','RARE RING OF EARTH','ring','/images/item/rare-ring-of-earth.png','{"health.min":220,"health.max":550,"earth-damage.min":50,"earth-damage.max":100,"earth-resist.min":20,"earth-resist.max":45}',now(),now()),
(22025,2,120,'rare-ring-of-light','RARE RING OF LIGHT','ring','/images/item/rare-ring-of-light.png','{"health.min":220,"health.max":550,"lightning-damage.min":50,"lightning-damage.max":100,"lightning-resist.min":20,"lightning-resist.max":45}',now(),now()),

(22031,3,120,'epic-ring-of-water','EPIC RING OF WATER','ring','/images/item/epic-ring-of-water.png','{"health.min":300,"health.max":600,"water-damage.min":100,"water-damage.max":200,"water-resist.min":25,"water-resist.max":55}',now(),now()),
(22032,3,120,'epic-ring-of-fire','EPIC RING OF FIRE','ring','/images/item/epic-ring-of-fire.png','{"health.min":300,"health.max":600,"fire-damage.min":100,"fire-damage.max":200,"fire-resist.min":25,"fire-resist.max":55}',now(),now()),
(22033,3,120,'epic-ring-of-wind','EPIC RING OF WIND','ring','/images/item/epic-ring-of-wind.png','{"health.min":300,"health.max":600,"wind-damage.min":100,"wind-damage.max":200,"wind-resist.min":25,"wind-resist.max":55}',now(),now()),
(22034,3,120,'epic-ring-of-earth','EPIC RING OF EARTH','ring','/images/item/epic-ring-of-earth.png','{"health.min":300,"health.max":600,"earth-damage.min":100,"earth-damage.max":200,"earth-resist.min":25,"earth-resist.max":55}',now(),now()),
(22035,3,120,'epic-ring-of-light','EPIC RING OF LIGHT','ring','/images/item/epic-ring-of-light.png','{"health.min":300,"health.max":600,"lightning-damage.min":100,"lightning-damage.max":200,"lightning-resist.min":25,"lightning-resist.max":55}',now(),now()),

(22041,4,120,'legendary-ring-of-water','LEGENDARY RING OF WATER','ring','/images/item/legendary-ring-of-water.png','{"health.min":350,"health.max":700,"water-damage.min":200,"water-damage.max":300,"water-resist.min":30,"water-resist.max":65}',now(),now()),
(22042,4,120,'legendary-ring-of-fire','LEGENDARY RING OF FIRE','ring','/images/item/legendary-ring-of-fire.png','{"health.min":350,"health.max":700,"fire-damage.min":200,"fire-damage.max":300,"fire-resist.min":30,"fire-resist.max":65}',now(),now()),
(22043,4,120,'legendary-ring-of-wind','LEGENDARY RING OF WIND','ring','/images/item/legendary-ring-of-wind.png','{"health.min":350,"health.max":700,"wind-damage.min":200,"wind-damage.max":300,"wind-resist.min":30,"wind-resist.max":65}',now(),now()),
(22044,4,120,'legendary-ring-of-earth','LEGENDARY RING OF EARTH','ring','/images/item/legendary-ring-of-earth.png','{"health.min":350,"health.max":700,"earth-damage.min":200,"earth-damage.max":300,"earth-resist.min":30,"earth-resist.max":65}',now(),now()),
(22045,4,120,'legendary-ring-of-light','LEGENDARY RING OF LIGHT','ring','/images/item/legendary-ring-of-light.png','{"health.min":350,"health.max":700,"lightning-damage.min":200,"lightning-damage.max":300,"lightning-resist.min":30,"lightning-resist.max":65}',now(),now()),

(22051,5,120,'relic-ring-of-water','RELIC RING OF WATER','ring','/images/item/relic-ring-of-water.png','{"health.min":400,"health.max":800,"water-damage.min":300,"water-damage.max":500,"water-resist.min":35,"water-resist.max":75}',now(),now()),
(22052,5,120,'relic-ring-of-fire','RELIC RING OF FIRE','ring','/images/item/relic-ring-of-fire.png','{"health.min":400,"health.max":800,"fire-damage.min":300,"fire-damage.max":500,"fire-resist.min":35,"fire-resist.max":75}',now(),now()),
(22053,5,120,'relic-ring-of-wind','RELIC RING OF WIND','ring','/images/item/relic-ring-of-wind.png','{"health.min":400,"health.max":800,"wind-damage.min":300,"wind-damage.max":500,"wind-resist.min":35,"wind-resist.max":75}',now(),now()),
(22054,5,120,'relic-ring-of-earth','RELIC RING OF EARTH','ring','/images/item/relic-ring-of-earth.png','{"health.min":400,"health.max":800,"earth-damage.min":300,"earth-damage.max":500,"earth-resist.min":35,"earth-resist.max":75}',now(),now()),
(22055,5,120,'relic-ring-of-light','RELIC RING OF LIGHT','ring','/images/item/relic-ring-of-light.png','{"health.min":400,"health.max":800,"lightning-damage.min":300,"lightning-damage.max":500,"lightning-resist.min":35,"lightning-resist.max":75}',now(),now()),




(23001,5,100,'souleater','SOULEATER','weapon','/images/item/souleater.png','{"health.min":75,"health.max":155,"attack.min":220,"attack.max":240,"defense.min":12,"defense.max":20,"speed.min":1,"speed.max":1,"fire-damage.min":5,"fire-damage.max":45}',now(),now()),
(23002,5,100,'nightguard','NIGHTGUARD','weapon','/images/item/nightguard.png','{"health.min":100,"health.max":180,"attack.min":305,"attack.max":315,"defense.min":15,"defense.max":27,"speed.min":1.6,"speed.max":1.3,"lightning-damage.min":5,"lightning-damage.max":63}',now(),now()),
(23003,5,100,'titanslayer','TITANSLAYER','weapon','/images/item/titanslayer.png','{"health.min":125,"health.max":200,"attack.min":415,"attack.max":440,"defense.min":10,"defense.max":18,"speed.min":2.2,"speed.max":1.8,"earth-damage.min":5,"earth-damage.max":90}',now(),now()),
(23004,6,100,'fire-tongue','FIRE TONGUE','weapon','/images/item/fire-tongue.png','{"health.min":50,"health.max":300,"attack.min":50,"attack.max":300,"defense.min":10,"defense.max":30,"speed.min":3.3,"speed.max":1.3,"fire-damage.min":35,"fire-damage.max":215,"wind-resist.min":15,"wind-resist.max":25}',now(),now()),
(23005,5,100,'silent-string','SILENT STRING','weapon','/images/item/silent-string.png','{"health.min":150,"health.max":225,"attack.min":455,"attack.max":490,"defense.min":8,"defense.max":14,"speed.min":2.4,"speed.max":2,"wind-damage.min":5,"wind-damage.max":105}',now(),now()),
(23006,6,100,'spiders-claw','SPIDER\'S CLAW','weapon','/images/item/spiders-claw.png','{"health.min":150,"health.max":600,"attack.min":35,"attack.max":350,"defense.min":10,"defense.max":50,"speed.min":2.2,"speed.max":1,"lightning-damage.min":20,"lightning-damage.max":225,"earth-resist.min":10,"earth-resist.max":50}',now(),now()),
(23007,5,100,'willbreaker','WILLBREAKER','weapon','/images/item/willbreaker.png','{"health.min":50,"health.max":135,"attack.min":5,"attack.max":195,"defense.min":14,"defense.max":23,"speed.min":1,"speed.max":0.8,"water-damage.min":5,"water-damage.max":34}',now(),now()),
(23008,6,100,'minotaurs-pride','MINOTAUR\'S PRIDE','weapon','/images/item/minotaurs-pride.png','{"health.min":100,"health.max":800,"attack.min":50,"attack.max":400,"defense.min":10,"defense.max":50,"speed.min":3,"speed.max":1.2,"wind-damage.min":20,"wind-damage.max":250,"water-resist.min":10,"water-resist.max":50}',now(),now()),
(23009,6,100,'necromancer-teeth','NECROMANCER TEETH','weapon','/images/item/necromancer-teeth.png','{"health.min":50,"health.max":500,"attack.min":25,"attack.max":250,"defense.min":10,"defense.max":50,"speed.min":2,"speed.max":0.8,"water-damage.min":15,"water-damage.max":180,"fire-resist.min":10,"fire-resist.max":50}',now(),now()),
(23010,6,100,'spear-of-the-gods','SPEAR OF THE GODS','weapon','/images/item/spear-of-the-gods.png','{"health.min":250,"health.max":600,"attack.min":100,"attack.max":275,"defense.min":20,"defense.max":75,"speed.min":2,"speed.max":0.8,"earth-damage.min":60,"earth-damage.max":250,"lightning-resist.min":50,"lightning-resist.max":100}',now(),now()),
(23011,3,100,'sword-of-marriage','SWORD OF MARRIAGE','weapon','/images/item/sword-of-marriage.png','{"attack.min":180,"attack.max":220,"speed.min":1.7,"speed.max":1.3}',now(),now()),
(23012,2,100,'elven-legend','ELVEN LEGEND','weapon','/images/item/elven-legend.png','{"attack.min":60,"attack.max":80,"speed.min":0.9,"speed.max":0.7}',now(),now()),
(23013,1,150,'dragons-claw','DRAGON\'S CLAW','weapon','/images/item/dragons-claw.png','{"attack.min":170,"attack.max":210,"speed.min":3.5,"speed.max":3.5}',now(),now()),
(23014,3,120,'ice-storm-blade','ICE STORM BLADE','weapon','/images/item/ice-storm-blade.png','{"attack.min":130,"attack.max":160,"speed.min":1.2,"speed.max":1.0}',now(),now()),
(23015,1,160,'ice-shard','ICE SHARD','weapon','/images/item/ice-shard.png','{"attack.min":66,"attack.max":74,"speed.min":1.3,"speed.max":1.3}',now(),now()),
(23016,2,140,'fiery-fang','FIERY FANG','weapon','/images/item/fiery-fang.png','{"attack.min":180,"attack.max":210,"speed.min":2.2,"speed.max":2.0}',now(),now()),
(23017,3,130,'blade-of-fire','BLADE OF FIRE','weapon','/images/item/blade-of-fire.png','{"attack.min":300,"attack.max":350,"speed.min":2.4,"speed.max":2.2}',now(),now()),
(23018,3,110,'bone-crusher','THE BONE CRUSHER','weapon','/images/item/the-bone-crusher.png','{"attack.min":255,"attack.max":345,"speed.min":2.4,"speed.max":2.0}',now(),now()),
(23019,4,100,'blade-of-the-damned','BLADE OF THE DAMNED','weapon','/images/item/blade-of-the-damned.png','{"health.min":0,"health.max":50,"attack.min":345,"attack.max":405,"speed.min":2.2,"speed.max":1.8}',now(),now()),
(23020,4,110,'kings-judgement','THE KING\'S JUDGEMENT','weapon','/images/item/the-kings-judgement.png','{"health.min":0,"health.max":75,"attack.min":200,"attack.max":240,"speed.min":1.3,"speed.max":1.1}',now(),now()),
(23021,4,130,'dragons-wrath','DRAGON\'S WRATH','weapon','/images/item/dragons-wrath.png','{"health.min":0,"health.max":100,"attack.min":355,"attack.max":445,"speed.min":2.2,"speed.max":2.0}',now(),now()),
(23022,4,120,'blizzard-of-doom','BLIZZARD OF DOOM','weapon','/images/item/blizzard-of-doom.png','{"health.min":0,"health.max":80,"attack.min":165,"attack.max":195,"speed.min":1.0,"speed.max":0.9}',now(),now()),
(23023,4,100,'axe-of-division','AXE OF DIVISION','weapon','/images/item/axe-of-division.png','{"health.min":25,"health.max":120,"attack.min":250,"attack.max":340,"defense.min":0,"defense.max":0,"speed.min":2.0,"speed.max":1.5,"fire-damage.min":30,"fire-damage.max":60}',now(),now()),
(23024,5,100,'uldreds-warfist','ULDRED\'S WARFIST','weapon','/images/item/uldreds-warfist.png','{"health.min":200,"health.max":320,"attack.min":700,"attack.max":800,"defense.min":22,"defense.max":28,"speed.min":3.5,"speed.max":3.0,"earth-damage.min":75,"earth-damage.max":200}',now(),now()),
(23025,5,100,'dungeon-warden','DUNGEON WARDEN','weapon','/images/item/dungeon-warden.png','{"health.min":160,"health.max":280,"attack.min":475,"attack.max":565,"defense.min":18,"defense.max":25,"speed.min":2.5,"speed.max":2.2,"earth-resist.min":20,"earth-resist.max":50}',now(),now()),
(23026,5,100,'hammer-of-doom','HAMMER OF DOOM','weapon','/images/item/hammer-of-doom.png','{"health.min":150,"health.max":250,"attack.min":350,"attack.max":425,"defense.min":15,"defense.max":30,"speed.min":2.2,"speed.max":1.7,"fire-damage.min":50,"fire-damage.max":120}',now(),now()),
(23027,7,110,'aquatic-edge','AQUATIC EDGE','weapon','/images/item/aquatic-edge.png','{"attack.min":250,"attack.max":450,"speed.min":3,"speed.max":1.5,"water-damage.min":250,"water-damage.max":500}',now(),now()),
(23028,7,120,'stormbreaker-blade','STORMBREAKER BLADE','weapon','/images/item/stormbreaker-blade.png','{"attack.min":250,"attack.max":450,"speed.min":2.8,"speed.max":1.3,"lightning-damage.min":100,"lightning-damage.max":500}',now(),now()),
(23029,7,130,'airheart-blade','AIRHEART BLADE','weapon','/images/item/airheart-blade.png','{"attack.min":220,"attack.max":475,"speed.min":3,"speed.max":1.2,"wind-damage.min":200,"wind-damage.max":475}',now(),now()),
(23030,7,130,'emberwrtah-sword','EMBERWRATH SWORD','weapon','/images/item/emberwrath-sword.png','{"attack.min":225,"attack.max":450,"speed.min":3.1,"speed.max":1.3,"fire-damage.min":150,"fire-damage.max":450}',now(),now()),
(23031,7,130,'naturesong-edge','NATURESONG EDGE','weapon','/images/item/naturesong-edge.png','{"health.min":600,"health.max":650,"attack.min":340,"attack.max":550,"speed.min":2.0,"speed.max":0.8,"earth-damage.min":500,"earth-damage.max":750}',now(),now()),



(24001,5,100,'barrier-of-none','BARRIER OF NONE','shield','/images/item/barrier-of-none.png','{"health.min":450,"health.max":720,"attack.min":30,"attack.max":50,"defense.min":50,"defense.max":63,"speed.min":-0.25,"speed.max":-0.5,"water-resist.min":10,"water-resist.max":50,"earth-resist.min":10,"earth-resist.max":50}',now(),now()),
(24002,5,100,'final-stand','FINAL STAND','shield','/images/item/final-stand.png','{"health.min":550,"health.max":765,"attack.min":35,"attack.max":41,"defense.min":58,"defense.max":59,"speed.min":-0.35,"speed.max":-0.45,"fire-resist.min":10,"fire-resist.max":50,"wind-resist.min":10,"wind-resist.max":50}',now(),now()),
(24003,6,100,'glory-shield','GLORY SHIELD','shield','/images/item/glory-shield.png','{"health.min":650,"health.max":1000,"attack.min":30,"attack.max":80,"defense.min":50,"defense.max":120,"speed.min":0,"speed.max":-0.4,"wind-resist.min":75,"wind-resist.max":150,"lightning-resist.min":75,"lightning-resist.max":150}',now(),now()),
(24004,5,100,'thousand-soul','THOUSAND SOUL','shield','/images/item/thousand-soul.png','{"health.min":500,"health.max":675,"attack.min":30,"attack.max":59,"defense.min":55,"defense.max":72,"speed.min":-0.3,"speed.max":-0.4,"wind-resist.min":10,"wind-resist.max":50,"lightning-resist.min":10,"lightning-resist.max":50}',now(),now()),
(24005,5,100,'uldreds-peace','ULDRED\'S PEACE','shield','/images/item/uldreds-peace.png','{"health.min":525,"health.max":840,"attack.min":30,"attack.max":50,"defense.min":50,"defense.max":70,"speed.min":-0.3,"speed.max":-0.45,"earth-damage.min":30,"earth-damage.max":70}',now(),now()),
(24006,2,100,'hoarfrost-shield','HOARFROST SHIELD','shield','/images/item/hoarfrost-shield.png','{"defense.min":11,"defense.max":19,"speed.min":-0.05,"speed.max":-0.15}',now(),now()),
(24007,3,100,'white-shell','WHITE SHELL','shield','/images/item/white-shell.png','{"health.min":255,"health.max":350,"defense.min":20,"defense.max":30,"speed.min":-0.05,"speed.max":-0.15}',now(),now()),
(24008,1,100,'bone-shield','BONE SHIELD','shield','/images/item/bone-shield.png','{"defense.min":9,"defense.max":15,"speed.min":0.2,"speed.max":0.15}',now(),now()),
(24009,2,100,'elven-protector','ELVEN PROTECTOR','shield','/images/item/elven-protector.png','{"defense.min":6,"defense.max":10,"speed.min":-0.1,"speed.max":-0.2}',now(),now()),
(24010,3,100,'nightmare-shield','NIGHTMARE SHIELD','shield','/images/item/nightmare-shield.png','{"health.min":0,"health.max":100,"defense.min":25,"defense.max":35,"speed.min":0.3,"speed.max":0.15}',now(),now()),
(24011,2,100,'undead-wall','UNDEAD WALL','shield','/images/item/undead-wall.png','{"defense.min":14,"defense.max":22,"speed.min":0.6,"speed.max":0.15}',now(),now()),
(24012,3,100,'elven-queens-shield','ELVEN QUEEN\'S SHIELD','shield','/images/item/elven-queens-shield.png','{"health.min":230,"health.max":270,"defense.min":15,"defense.max":25,"speed.min":-0.2,"speed.max":-0.4}',now(),now()),
(24013,1,100,'ice-floe','ICE FLOE','shield','/images/item/ice-floe.png','{"defense.min":8,"defense.max":14,"speed.min":0,"speed.max":0}',now(),now()),
(24014,1,100,'dragon-crust','DRAGON CRUST','shield','/images/item/dragon-crust.png','{"defense.min":10,"defense.max":18,"speed.min":0.1,"speed.max":0.1}',now(),now()),
(24015,2,100,'ancient-scale','ANCIENT SCALE','shield','/images/item/ancient-scale.png','{"defense.min":10,"defense.max":18,"speed.min":0.1,"speed.max":0.1}',now(),now()),
(24016,3,100,'dragons-shield','DRAGON\'S SHIELD','shield','/images/item/dragons-shield.png','{"health.min":90,"health.max":250,"defense.min":24,"defense.max":32,"speed.min":-0.15,"speed.max":-0.25}',now(),now()),
(24017,4,100,'ward-of-souls','WARD OF SOULS','shield','/images/item/ward-of-souls.png','{"health.min":200,"health.max":450,"attack.min":0,"attack.max":20,"defense.min":30,"defense.max":50,"speed.min":-0.3,"speed.max":-0.5}',now(),now()),
(24018,4,100,'royal-blessing','ROYAL BLESSING','shield','/images/item/royal-blessing.png','{"health.min":355,"health.max":450,"attack.min":0,"attack.max":10,"defense.min":20,"defense.max":40,"speed.min":-0.2,"speed.max":-0.4}',now(),now()),
(24019,4,100,'glacier-wall','GLACIER WALL','shield','/images/item/glacier-wall.png','{"health.min":550,"health.max":650,"attack.min":0,"attack.max":15,"defense.min":25,"defense.max":45,"speed.min":-0.1,"speed.max":-0.3}',now(),now()),
(24020,4,100,'primal-ward','PRIMAL WARD','shield','/images/item/primal-ward.png','{"health.min":300,"health.max":400,"attack.min":0,"attack.max":25,"defense.min":35,"defense.max":55,"speed.min":-0.3,"speed.max":-0.5}',now(),now()),
(24021,5,100,'underworlds-guardian','UNDERWORLD\'S GUARDIAN','shield','/images/item/underworlds-guardian.png','{"health.min":475,"health.max":745,"attack.min":30,"attack.max":70,"defense.min":45,"defense.max":86,"speed.min":-0.25,"speed.max":-0.40,"fire-resist.min":50,"fire-resist.max":100}',now(),now()),
(24022,5,100,'face-of-mitar','FACE OF MITAR','shield','/images/item/face-of-mitar.png','{"health.min":425,"health.max":795,"attack.min":30,"attack.max":60,"defense.min":40,"defense.max":75,"speed.min":-0.20,"speed.max":-0.50,"earth-resist.min":50,"earth-resist.max":100}',now(),now()),
(24023,5,100,'medusas-vision','MEDUSA\'S VISION','shield','/images/item/medusas-vision.png','{"health.min":250,"health.max":1200,"defense.min":30,"defense.max":100,"speed.min":0.20,"speed.max":-0.40}',now(),now()),
(24024,7,110,'tempest-guard','TEMPEST GUARD','shield','/images/item/tempest-guard.png','{"health.min":500,"health.max":1000,"defense.min":60,"defense.max":150,"speed.min":0,"speed.max":-0.20,"water-resist.min":100,"water-resist.max":200,"lightning-resist.min":100,"lightning-resist.max":200}',now(),now()),
(24025,7,120,'thunderclap-barrier','THUNDERCLAP BARRIER','shield','/images/item/thunderclap-barrier.png','{"health.min":600,"health.max":1100,"defense.min":60,"defense.max":150,"speed.min":0,"speed.max":-0.10,"earth-damage.min":50,"earth-damage.max":150,"lightning-resist.min":50,"lightning-resist.max":150}',now(),now()),
(24026,7,130,'skyblaze-ward','SKYBLAZE WARD','shield','/images/item/skyblaze-ward.png','{"health.min":550,"health.max":1150,"defense.min":50,"defense.max":175,"speed.min":0,"speed.max":-0.10,"fire-resist.min":50,"fire-resist.max":150,"wind-resist.min":50,"wind-resist.max":150}',now(),now()),
(24027,7,130,'pyroclasm-aegis','PYROCLASM AEGIS','shield','/images/item/pyroclasm-aegis.png','{"health.min":650,"health.max":1000,"defense.min":60,"defense.max":170,"speed.min":0,"speed.max":-0.30,"fire-resist.min":50,"fire-resist.max":150,"earth-resist.min":50,"earth-resist.max":150}',now(),now()),
(24028,7,130,'terraflora-shield','TERRAFLORA SHIELD','shield','/images/item/terraflora-shield.png','{"health.min":1200,"health.max":2000,"attack.min":40,"attack.max":100,"defense.min":150,"defense.max":250,"speed.min":-0.30,"speed.max":-0.50,"water-resist.min":200,"water-resist.max":300,"earth-resist.min":200,"earth-resist.max":300}',now(),now()),



(25001,5,100,'divine-spring-hammer','DIVINE SPRING HAMMER','weapon-skin','/images/item/divine-spring-hammer.png','{"health.min":500,"health.max":500,"earth-resist.min":20,"earth-resist.max":40}',now(),now()),
(25002,5,100,'divine-astral-defender','DIVINE ASTRAL DEFENDER','shield-skin','/images/item/divine-astral-defender.png','{"health.min":500,"health.max":500,"lightning-resist.min":20,"lightning-resist.max":40}',now(),now()),
(25003,5,100,'divine-breath-of-the-leech','DIVINE BREATH OF THE LEECH','shield-skin','/images/item/divine-breath-of-the-leech.png','{"health.min":500,"health.max":500,"fire-resist.min":20,"fire-resist.max":40}',now(),now()),
(25004,5,100,'divine-astral-mace','DIVINE ASTRAL MACE','weapon-skin','/images/item/divine-astral-mace.png','{"health.min":500,"health.max":500,"lightning-resist.min":20,"lightning-resist.max":40}',now(),now()),
(25005,5,100,'divine-vampire-bite','DIVINE VAMPIRE BITE','weapon-skin','/images/item/divine-vampire-bite.png','{"health.min":500,"health.max":500,"wind-resist.min":20,"wind-resist.max":40}',now(),now()),
(25006,5,100,'divine-greenstone-shield','DIVINE GREENSTONE SHIELD','shield-skin','/images/item/divine-greenstone-shield.png','{"health.min":500,"health.max":500,"earth-resist.min":20,"earth-resist.max":40}',now(),now()),
(25007,5,100,'divine-captains-steerwheel','DIVINE CAPTAIN\'S STEERWHEEL','shield-skin','/images/item/divine-captains-steerwheel.png','{"health.min":500,"health.max":500,"water-resist.min":20,"water-resist.max":40}',now(),now()),
(25008,5,100,'divine-vampire-shield','DIVINE VAMPIRE SHIELD','shield-skin','/images/item/divine-vampire-shield.png','{"health.min":500,"health.max":500,"wind-resist.min":20,"wind-resist.max":40}',now(),now()),
(25009,5,100,'divine-swordfish','DIVINE SWORDFISH','weapon-skin','/images/item/divine-swordfish.png','{"health.min":500,"health.max":500,"water-resist.min":20,"water-resist.max":40}',now(),now()),
(25010,5,100,'divine-diabolic-trident','DIVINE DIABOLIC TRIDENT','weapon-skin','/images/item/divine-diabolic-trident.png','{"health.min":500,"health.max":500,"fire-resist.min":20,"fire-resist.max":40}',now(),now()),

(99999,null,null,'none','NONE','none','','',now(),now())
;
