-- =========== LOCATION =======================================

truncate location;
insert into location (id,name,label,region,area,section,floor,room) values
(1100,'city','City','Nature Valley','City',NULL,NULL,NULL),
(1105,'city-guildhall','City - Guild Hall','Nature Valley','City','Guild Hall','1',NULL),
(1110,'city-city-market','City - City Market','Nature Valley','City','City Market','1',NULL),
(1115,'city-open-market','City - Open Market','Nature Valley','City','Open Market','1',NULL),
(1120,'city-top-patrons','City - Top Patrons','Nature Valley','City','Top Patrons','1',NULL),
(1125,'city-gate','City - City Gate','Nature Valley','City','City Gate','1',NULL),
(1130,'city-shadow-order','City - Shadow Order Entrance','Nature Valley','City','Shadow Order Entrance','1',NULL),
(1135,'city-graveyard','City - Graveyard Entrance','Nature Valley','City','Graveyard Entrance','1',NULL),



(3100,'shadow-order-dungeon','Shadow Order Dungeon','City','Shadow Order Dungeon',NULL,NULL,NULL),
(3105,'shadow-order-dungeon-entry','Shadow Order Dungeon - Entry','City','Shadow Order Dungeon','Entry','1',NULL),
(3110,'shadow-order-dungeon-main-hall-floor1','Shadow Order Dungeon - Main Hall - 1st Floor','City','Shadow Order Dungeon','Main Hall','1',NULL),
(3115,'shadow-order-dungeon-main-hall-floor2','Shadow Order Dungeon - Main Hall - 2nd Floor','City','Shadow Order Dungeon','Main Hall','2',NULL),
(3120,'shadow-order-dungeon-main-hall-floor3','Shadow Order Dungeon - Main Hall - 3rd Floor','City','Shadow Order Dungeon','Main Hall','3',NULL),
(3125,'shadow-order-dungeon-fire-1-room1','Shadow Order Dungeon - Fire 1 - 1st Room','City','Shadow Order Dungeon','Fire 1','1','1'),
(3130,'shadow-order-dungeon-fire-1-room2','Shadow Order Dungeon - Fire 1 - 2nd Room','City','Shadow Order Dungeon','Fire 1','1','2'),
(3135,'shadow-order-dungeon-water-1-room1','Shadow Order Dungeon - Water 1 - 1st Room','City','Shadow Order Dungeon','Water 1','1','1'),
(3140,'shadow-order-dungeon-water-1-room2','Shadow Order Dungeon - Water 1 - 2nd Room','City','Shadow Order Dungeon','Water 1','1','2'),
(3145,'shadow-order-dungeon-wind-1-room1','Shadow Order Dungeon - Wind 1 - 1st Room','City','Shadow Order Dungeon','Wind 1','1','1'),
(3150,'shadow-order-dungeon-wind-1-room2','Shadow Order Dungeon - Wind 1 - 2nd Room','City','Shadow Order Dungeon','Wind 1','1','2'),
(3155,'shadow-order-dungeon-earth-1-room1','Shadow Order Dungeon - Earth 1 - 1st Room','City','Shadow Order Dungeon','Earth 1','1','1'),
(3160,'shadow-order-dungeon-earth-1-room2','Shadow Order Dungeon - Earth 1 - 2nd Room','City','Shadow Order Dungeon','Earth 1','1','2'),
(3165,'shadow-order-dungeon-lightning-1-room1','Shadow Order Dungeon - Lightning 1 - 1st Room','City','Shadow Order Dungeon','Lightning 1','1','1'),
(3170,'shadow-order-dungeon-lightning-1-room2','Shadow Order Dungeon - Lightning 1 - 2nd Room','City','Shadow Order Dungeon','Lightning 1','1','2'),
(3175,'shadow-order-dungeon-fire-2-room1','Shadow Order Dungeon - Fire 2 - 1st Room','City','Shadow Order Dungeon','Fire 2','1','1'),
(3180,'shadow-order-dungeon-fire-2-room2','Shadow Order Dungeon - Fire 2 - 2nd Room','City','Shadow Order Dungeon','Fire 2','1','2'),
(3185,'shadow-order-dungeon-water-2-room1','Shadow Order Dungeon - Water 2 - 1st Room','City','Shadow Order Dungeon','Water 2','1','1'),
(3190,'shadow-order-dungeon-water-2-room2','Shadow Order Dungeon - Water 2 - 2nd Room','City','Shadow Order Dungeon','Water 2','1','2'),
(3195,'shadow-order-dungeon-wind-2-room1','Shadow Order Dungeon - Wind 2 - 1st Room','City','Shadow Order Dungeon','Wind 2','1','1'),
(3200,'shadow-order-dungeon-wind-2-room2','Shadow Order Dungeon - Wind 2 - 2nd Room','City','Shadow Order Dungeon','Wind 2','1','2'),
(3205,'shadow-order-dungeon-earth-2-room1','Shadow Order Dungeon - Earth 2 - 1st Room','City','Shadow Order Dungeon','Earth 2','1','1'),
(3210,'shadow-order-dungeon-earth-2-room2','Shadow Order Dungeon - Earth 2 - 2nd Room','City','Shadow Order Dungeon','Earth 2','1','2'),
(3215,'shadow-order-dungeon-lightning-2-room1','Shadow Order Dungeon - Lightning 2 - 1st Room','City','Shadow Order Dungeon','Lightning 2','1','1'),
(3220,'shadow-order-dungeon-lightning-2-room2','Shadow Order Dungeon - Lightning 2 - 2nd Room','City','Shadow Order Dungeon','Lightning 2','1','2'),

(3300,'guildhall','Guild Hall','City','Guild Hall',NULL,NULL,NULL),
(3325,'guildhall-guild-dungeon-entry','Guild Hall - Guild Dungeon','City','Guild Hall','Guild Dungeon Entrance','1',NULL),

(3400,'golden-dragon-den','Golden Dragon Den','City','Golden Dragon Den',NULL,NULL,NULL),
(3500,'sapphire-dragon-den','Sapphire Dragon Den','City','Sapphire Dragon Den',NULL,NULL,NULL),

(3600,'graveyard','Graveyard','City','Graveyard',NULL,NULL,NULL),

(1200,'nature-valley-east','Nature Valley East','Nature Valley','Nature Valley East',NULL,NULL,NULL),
(1205,'nature-valley-east-fishing','Nature Valley East - Fishing Entrance','Nature Valley','Nature Valley East','Fishing Entrance','1',NULL),

(1300,'virimel','Virimel Village','Nature Valley','Virimel Village',NULL,NULL,NULL),
(1305,'virimel-airport','Virimel Village - Airport','Nature Valley','Virimel Village','Airport','1',NULL),
(1310,'virimel-forge','Virimel Village - Forge','Nature Valley','Virimel Village','Forge','1',NULL),
(1315,'virimel-trainer-house','Virimel Village - Trainer House','Nature Valley','Virimel Village','Trainer House','1',NULL),
(1320,'virimel-market','Virimel Village - Market','Nature Valley','Virimel Village','Market','1',NULL),
(1325,'virimel-wood','Virimel Village Tree - Wood - Snails','Nature Valley','Virimel Village','Tree','1',NULL),
(1330,'virimel-stone-cave','Virimel Village - Stone Cave Entrance','Nature Valley','Virimel Village','Stone Cave Entrance','1',NULL),
(1335,'virimel-house','Virimel Village - House','Nature Valley','Virimel Village','House','1',NULL),
(1340,'virimel-totem','Virimel Village - Totem','Nature Valley','Virimel Village','Totem','1',NULL),
(1345,'virimel-inn','Virimel Village - Inn','Nature Valley','Virimel Village','Inn','1',NULL),
(1350,'virimel-goblin-silo','Virimel Village - Goblin Silo','Nature Valley','Virimel Village','Goblin Silo','1',NULL),

(1400,'stone-cave','Stone Cave','Nature Valley','Stone Cave',NULL,NULL,NULL),
(1405,'stone-cave-floor1','Stone Cave 1st Floor - Stone - Crab','Nature Valley','Stone Cave','Stone Mine','1',NULL),
(1410,'stone-cave-floor2','Stone Cave 2nd Floor - Coal - Bat','Nature Valley','Stone Cave','Coal Mine','2',NULL),
(1415,'stone-cave-floor3','Stone Cave 3rd Floor - Iron - Rat','Nature Valley','Stone Cave','Iron Mine','3',NULL),
(1420,'stone-cave-floor4','Stone Cave 4th Floor - Gold - Cave Snail','Nature Valley','Stone Cave','Gold Mine','4',NULL),
(1425,'stone-cave-floor5','Stone Cave 5th Floor - Platinum - Bunny','Nature Valley','Stone Cave','Platinum Mine','5',NULL),
(1430,'stone-cave-floor6','Stone Cave 6th Floor - Tanzanite - Worm','Nature Valley','Stone Cave','Tanzanite Mine','6',NULL),
(1435,'stone-cave-floor7','Stone Cave 7th Floor - Goblins Gate','Nature Valley','Stone Cave','Goblins Gate','7',NULL),
(1440,'stone-cave-floor8','Stone Cave 8th Floor - Emerald - Chicken','Nature Valley','Stone Cave','Emerald Mine','8',NULL),
(1445,'stone-cave-floor8-enhance','Stone Cave 8th Floor - Enhancement Workshop','Nature Valley','Stone Cave','Enhancement Workshop','8',NULL),
(1450,'stone-cave-floor9','Stone Cave 9th Floor - Ruby - Mole','Nature Valley','Stone Cave','Ruby Mine','9',NULL),
(1455,'stone-cave-floor10','Stone Cave 10th Floor - Jade - Duck','Nature Valley','Stone Cave','Jade Mine','10',NULL),
(1460,'stone-cave-floor11','Stone Cave 11th Floor - Insatiable Ore - Piggy','Nature Valley','Stone Cave','Insatiable Ore Mine','11',NULL),
(1465,'stone-cave-floor12','Stone Cave 12th Floor - Insatiable Cracked Stone - Buffalo','Nature Valley','Stone Cave','Insatiable Cracked Stone Mine','12',NULL),
(1470,'stone-cave-floor12-necromancers-altar','Stone Cave 12th Floor - Necromancer\'s Altar Entrance','Nature Valley','Stone Cave','Necromancer\'s Altar Entrance','12',NULL),

(1500,'necromancers-altar','Necromancer\'s Altar','Nature Valley','Necromancer\'s Altar',NULL,NULL,NULL),
(1505,'necromancers-altar-floor1','Necromancer\'s Altar 1st Floor','Nature Valley','Necromancer\'s Altar','1st Floor','1',NULL),
(1510,'necromancers-altar-floor2','Necromancer\'s Altar 2nd Floor - Skeleton','Nature Valley','Necromancer\'s Altar','2nd Floor','2',NULL),
(1515,'necromancers-altar-floor3','Necromancer\'s Altar 3rd Floor - Skeleton Shield','Nature Valley','Necromancer\'s Altar','3rd Floor','3',NULL),
(1520,'necromancers-altar-floor4','Necromancer\'s Altar 4th Floor - Ghost','Nature Valley','Necromancer\'s Altar','4th Floor','4',NULL),
(1525,'necromancers-altar-floor5','Necromancer\'s Altar 5th Floor - Skeleton Mage','Nature Valley','Necromancer\'s Altar','5th Floor','5',NULL),
(1530,'necromancers-altar-floor6','Necromancer\'s Altar 6th Floor - Skeleton Axe','Nature Valley','Necromancer\'s Altar','6th Floor','6',NULL),
(1535,'necromancers-altar-floor7','Necromancer\'s Altar 7th Floor - Skeleton Champion','Nature Valley','Necromancer\'s Altar','7th Floor','7',NULL),
(1540,'necromancers-altar-floor8','Necromancer\'s Altar 8th Floor - Necromancer','Nature Valley','Necromancer\'s Altar','8th Floor','8',NULL),

(1600,'nature-valley-west','Nature Valley West','Nature Valley','Nature Valley West',NULL,NULL,NULL),
(1605,'nature-valley-west-bridge','Nature Valley West - Bridge','Nature Valley','Nature Valley West','Bridge','1',NULL),
(1610,'nature-valley-west-event-gate','Nature Valley West - Event Gate','Nature Valley','Nature Valley West','Event Gate','1',NULL),
(1615,'nature-valley-west-dungeon','Nature Valley West - Dungeon Entrance','Nature Valley','Nature Valley West','Dungeon Entrance','1',NULL),

(1700,'dungeon','Dungeon','Nature Valley','Dungeon',NULL,NULL,NULL),
(1705,'dungeon-floor1','Dungeon 1st Floor - Rat','Nature Valley','Dungeon','1st Floor','1',NULL),
(1710,'dungeon-floor2','Dungeon 2nd Floor - Slime','Nature Valley','Dungeon','2nd Floor','2',NULL),
(1715,'dungeon-floor3','Dungeon 3rd Floor - Goblin','Nature Valley','Dungeon','3rd Floor','3',NULL),
(1720,'dungeon-floor4','Dungeon 4th Floor - Goblin Leader','Nature Valley','Dungeon','4th Floor','4',NULL),
(1725,'dungeon-floor5','Dungeon 5th Floor - Oculothorax','Nature Valley','Dungeon','5th Floor','5',NULL),
(1730,'dungeon-floor6','Dungeon 6th Floor - Bandit','Nature Valley','Dungeon','6th Floor','6',NULL),
(1735,'dungeon-floor7','Dungeon 7th Floor - Ogr','Nature Valley','Dungeon','7th Floor','7',NULL),
(1740,'dungeon-floor8','Dungeon 8th Floor - Troll','Nature Valley','Dungeon','8th Floor','8',NULL),
(1745,'dungeon-floor9','Dungeon 9th Floor - Fire Wisp','Nature Valley','Dungeon','9th Floor','9',NULL),
(1750,'dungeon-floor10','Dungeon 10th Floor - Water Wisp','Nature Valley','Dungeon','10th Floor','10',NULL),
(1755,'dungeon-floor11','Dungeon 11th Floor - Wind Wisp','Nature Valley','Dungeon','11th Floor','11',NULL),
(1760,'dungeon-floor12','Dungeon 12th Floor - Earth Elemental','Nature Valley','Dungeon','12th Floor','12',NULL),
(1765,'dungeon-floor13','Dungeon 13th Floor - Dungeon King','Nature Valley','Dungeon','13th Floor','13',NULL),

(1800,'uber-scroll-portal','Uber Scroll Portal - Archangel','Scroll Portal','Uber Scroll Portal','Archangel','1',NULL),
(1805,'great-council-portal','The Great Council Portal - Lord of Dissection','Scroll Portal','The Great Council Portal','Lord of Dissection','1',NULL),

(1900,'mystic-frozen-tower','Mystic Frozen Tower','Nature Valley','Mystic Frozen Tower',NULL,NULL,NULL),

(2300,'ruins-of-elven-temple','Ruins of Elven Temple','Nature Valley','Ruins of Elven Temple',NULL,NULL,NULL),

(2400,'mitar','Mitar','Ruins of Elven Temple','Mitar',NULL,NULL,NULL),
(2405,'mitar-entrance','Mitar Entrance','Ruins of Elven Temple','Mitar','Entrance','1','1'),
(2410,'mitar-forge','Mitar Forge','Ruins of Elven Temple','Mitar','Forge','1','2'),
(2415,'mitar-statues','Mitar Statues','Ruins of Elven Temple','Mitar','Statues','1','3'),
(2420,'mitar-mines-room1','Mitar Mines 1st Room - Goblin Knocker','Ruins of Elven Temple','Mitar','1st Room','2','1'),
(2425,'mitar-mines-room2','Mitar Mines 2nd Room - Hobgoblin','Ruins of Elven Temple','Mitar','2nd Room','2','2'),
(2430,'mitar-mines-room3','Mitar Mines 3rd Room - Stone Spider','Ruins of Elven Temple','Mitar','3rd Room','2','3'),
(2435,'mitar-mines-room4','Mitar Mines 4th Room - Uhr-Rahz','Ruins of Elven Temple','Mitar','4th Room','2','4'),
(2440,'mitar-mines-room5','Mitar Mines 5th Room - Uhr-Rahz Portal','Ruins of Elven Temple','Mitar','5th Room','2','5'),
(2445,'mitar-mines-room6','Mitar Mines 6th Room - Orc Grunt','Ruins of Elven Temple','Mitar','6th Room','2','6'),
(2450,'mitar-mines-room7','Mitar Mines 7th Room - Giant Bat','Ruins of Elven Temple','Mitar','7th Room','2','7'),
(2455,'mitar-mines-room8','Mitar Mines 8th Room - Stone Wurming','Ruins of Elven Temple','Mitar','8th Room','2','8'),
(2460,'mitar-mines-room9','Mitar Mines 9th Room - Five Gates Puzzle','Ruins of Elven Temple','Mitar','9th Room','2','9'),
(2465,'mitar-mines-room10','Mitar Mines 10th Room - Sharra Portal','Ruins of Elven Temple','Mitar','10th Room','2','10'),
(2470,'mitar-mines-room11','Mitar Mines 11th Room - Sharra','Ruins of Elven Temple','Mitar','11th Room','2','11'),
(2475,'mitar-mines-room12','Mitar Mines 12th Room - Orc Champion','Ruins of Elven Temple','Mitar','12th Room','2','12'),
(2480,'mitar-mines-room13','Mitar Mines 13th Room - Stone Eater','Ruins of Elven Temple','Mitar','13th Room','2','13'),
(2485,'mitar-mines-room14','Mitar Mines 14th Room - Warboss','Ruins of Elven Temple','Mitar','14th Room','2','14'),
(2490,'mitar-mines-room15','Mitar Mines 15th Room - Raghor Portal','Ruins of Elven Temple','Mitar','15th Room','2','15'),
(2495,'mitar-mines-room16','Mitar Mines 16th Room - Raghor','Ruins of Elven Temple','Mitar','16th Room','2','16'),

(2500,'einlor','Einlor','Ruins of Elven Temple','Einlor',NULL,NULL,NULL),

(2900,'summoners-wall','Summoners Wall','Ruins of Elven Temple','Summoners Wall',NULL,NULL,NULL),

(2920,'archstone','Archstone','Ruins of Elven Temple','Archstone',NULL,NULL,NULL),
(2925,'archstone-red-dragon','Red Dragon','Ruins of Elven Temple','Archstone','Red Dragon','1','1'),
(2930,'archstone-wind-dragon','Wind Dragon','Ruins of Elven Temple','Archstone','Wind Dragon','2','1'),

(3000,'big-surprise-scroll','Big Surprise Scroll Portal','Scroll Portal','Big Surprise Scroll Portal','Big Surprise','1',NULL),
(3005,'pumpkin-reaper-scroll','Pumpkin Reaper Scroll Portal','Scroll Portal','Pumpkin Reaper Scroll Portal','Pumpkin Reaper','1',NULL),
(3010,'uber-medusa-scroll','Uber Medusa Scroll Portal','Scroll Portal','Uber Medusa Scroll Portal','Uber Medusa','1',NULL),
(3015,'uber-nemesis-scroll','Uber Nemesis Scroll Portal','Scroll Portal','Uber Nemesis Scroll Portal','Uber Nemesis','1',NULL),
(3020,'uber-minotaur-scroll','Uber Minotaur Scroll Portal','Scroll Portal','Uber Minotaur Scroll Portal','Uber Minotaur','1',NULL),
(3025,'uber-spartan-scroll','Uber Spartan Scroll Portal','Scroll Portal','Uber Spartan Scroll Portal','Uber Spartan','1',NULL),


(99999,'event','Event','Event','Event',NULL,NULL,NULL)
;
